# This file was generated by GoReleaser. DO NOT EDIT.
class Gotransit < Formula
  desc "Library and tool for reading, writing, and processing transit data"
  homepage "https://github.com/interline-io/gotransit"
  version "0.2.1-rc2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/interline-io/gotransit/releases/download/v0.2.1-rc2/gotransit_0.2.1-rc2_darwin_amd64.tar.gz"
    sha256 "09d869b793fa49387211fc9ab8316cd0ffee3f735b48655bb58cabf41e0d5181"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/interline-io/gotransit/releases/download/v0.2.1-rc2/gotransit_0.2.1-rc2_linux_amd64.tar.gz"
      sha256 "1e5edaad848d7c0ead29ea884c792d14d9217c3e978d21baa0295c1d51cb767b"
    end
  end

  def install
    bin.install "gotransit"
  end
end
